export const ROLE_PERMISSIONS = {
  owner: ['*'],
  manager: [
    'dashboard:read',
    'pos:use',
    'products:read',
    'products:write',
    'inventory:read',
    'inventory:write',
    'purchases:read',
    'purchases:write',
    'suppliers:read',
    'suppliers:write',
    'customers:read',
    'customers:write',
    'sales:read',
    'sales:write',
    'sales:refund',
    'payments:read',
    'payments:write',
    'expenses:read',
    'expenses:write',
    'reports:read',
    'branches:read',
    'branches:write',
    'users:read',
    'users:write',
    'users:invite',
    'notifications:read',
    'notifications:write',
    'sync:use',
    'backup:read',
    'backup:write',
    'settings:read',
    'settings:write',
    'bank_accounts:read',
    'bank_accounts:write',
    'shifts:read',
    'shifts:write',
    'stocktake:read',
    'stocktake:write',
    'audit:read',
    'subscription:read',
    'subscription:write',
    'push:write',
    // P2
    'ai:use',
    'loyalty:read',
    'loyalty:write',
    'pricing:read',
    'pricing:write',
    'recipes:read',
    'recipes:write',
    'manufacturing:read',
    'manufacturing:write',
    'import:use',
    'export:use',
    'mobile:use',
  ],
  cashier: [
    'pos:use',
    'products:read',
    'customers:read',
    'customers:write',
    'sales:read',
    'sales:write',
    'sales:refund',
    'payments:read',
    'notifications:read',
    'sync:use',
    'shifts:read',
    'shifts:write',
    'loyalty:read',
    'loyalty:write',
    'pricing:read',
    'mobile:use',
  ],
  warehouse: [
    'products:read',
    'products:write',
    'inventory:read',
    'inventory:write',
    'purchases:read',
    'purchases:write',
    'suppliers:read',
    'suppliers:write',
    'stocktake:read',
    'stocktake:write',
    'notifications:read',
    'sync:use',
    'recipes:read',
    'recipes:write',
    'manufacturing:read',
    'manufacturing:write',
    'import:use',
    'export:use',
    'mobile:use',
  ],
  accountant: [
    'dashboard:read',
    'purchases:read',
    'suppliers:read',
    'customers:read',
    'sales:read',
    'payments:read',
    'payments:write',
    'expenses:read',
    'expenses:write',
    'reports:read',
    'bank_accounts:read',
    'shifts:read',
    'audit:read',
    'notifications:read',
    'sync:use',
    'subscription:read',
    'ai:use',
    'loyalty:read',
    'pricing:read',
    'export:use',
    'mobile:use',
  ],
  superadmin: ['*', 'platform:*'],
};

export function hasPermission(role, permission) {
  const perms = ROLE_PERMISSIONS[role] || [];
  if (perms.includes('*') || perms.includes('platform:*')) return true;
  if (perms.includes(permission)) return true;
  if (permission.endsWith(':read')) {
    const write = permission.replace(':read', ':write');
    if (perms.includes(write)) return true;
  }
  return false;
}
